UPDDI/mps-database-server

compounds/ajax.py, compounds/static/compounds/compound_report.js, mps/templates/compounds/compounds_report.html
- Increase height of plots
- Decrease padding of table
- Bug fix for improper iteration
=> Compound Report Fixes

assays/static/assays/customize_chip_results_admin.js, assays/static/assays/customize_plate_results.js, compounds/static/compounds/compound_report.js, compounds/static/compounds/compound_update.js, compounds/static/compounds/customize_admin.js, drugtrials/static/drugtrials/compare_adverse_events.js, mps/static/js/inline_add.js, mps/templates/assays/assaychipreadout_add.html, mps/templates/assays/assaychipsetup_add.html, mps/templates/assays/assaychiptestresult_add.html, mps/templates/assays/assayplatereadout_add.html, mps/templates/assays/assayplatesetup_add.html, mps/templates/assays/assayplatetestresult_add.html, mps/templates/assays/studyconfiguration_add.html, mps/templates/compounds/compounds_add.html, mps/templates/compounds/compounds_update.html, mps/templates/microdevices/organ_model_add.html
-Make inlines more general such that the script works with multiple inlines
-Resolve performance issues when loading selections
=> Changes to Inlines and Saved Selections

bioactivities/parsers.py, bioactivities/static/bioactivities/filter.js, bioactivities/static/bioactivities/table.js, bioactivities/templates/bioactivities/cluster.html, bioactivities/templates/bioactivities/table.html, compounds/models.py, compounds/static/compounds/compound_report.js, compounds/static/compounds/compounds_list.js, compounds/templates/compounds/compounds_add.html, compounds/templates/compounds/compounds_detail.html, compounds/templates/compounds/compounds_list.html, compounds/templates/compounds/compounds_report.html, drugtrials/static/drugtrials/adverse_events_list.js, drugtrials/static/drugtrials/drugtrial_list.js, drugtrials/templates/drugtrials/adverse_events_detail.html, drugtrials/templates/drugtrials/adverse_events_list.html, drugtrials/templates/drugtrials/drugtrial_detail.html, drugtrials/templates/drugtrials/drugtrial_list.html, microdevices/models.py, microdevices/static/microdevices/organmodel_list.js, microdevices/templates/microdevices/organmodel_add.html, microdevices/templates/microdevices/organmodel_detail.html, microdevices/templates/microdevices/organmodel_list.html, mps/static/js/display_datatable.js, mps/static/js/project_filter.js, mps/templates/base.html, mps/templates/index.html, mps/templates/project_filters.html
Adds filters for TCTC and fixes the following bugs with floating headers:
- Floating headers appearing when they should be hidden
- Floating header being offset to the right after a dialog window has been opened
=> Add TCTC Filters; Fix Floating Header Bugs

assays/templates/assays/assaychipreadout_add.html, assays/templates/assays/assaychipsetup_add.html, assays/templates/assays/assaychiptestresult_add.html, assays/templates/assays/assayplatereadout_add.html, assays/templates/assays/assayplatesetup_add.html, assays/templates/assays/assayplatetestresult_add.html, assays/templates/assays/assayrun_add.html, assays/views.py, microdevices/models.py, mps/templates/submit.html
Fixes some issues with signing off and changes breadcrumbs in setups, readouts, and results.
=> Hotfix: Fix sign off bugs

assays/admin.py, assays/ajax.py, assays/static/assays/assaychipreadout_add.js, assays/static/assays/assayplatereadout_add.js, assays/static/assays/chart_display.js, assays/static/assays/readoutbulkupload.js, assays/templates/assays/assayrun_add.html, microdevices/templates/microdevices/microdevice_list.html, mps/mixins.py, mps/templates/help.html
=> Minor Fixes

bioactivities/static/bioactivities/table.js, microdevices/admin.py, microdevices/forms.py, microdevices/models.py
Fix a bug in bioactivity table display and change admin interface for microphys center
=> Admin changes + bug fix

assays/migrations/0001_auto_20180104_1212.py, assays/migrations/0002_merge.py, assays/templates/assays/assaymatrix_add.html, assays/templates/assays/assaymatrix_detail.html, assays/templates/assays/email/tctc_stakeholder_email.txt, cellsamples/migrations/0001_auto_20180104_1212.py, cellsamples/migrations/0002_merge.py, microdevices/migrations/0001_auto_20180104_1212.py, microdevices/migrations/0002_merge.py, mps/templates/help.html
MPS UPDDI Admin,
Glossary terms have been added to the help template for terms for A to D for testing on stage. Glossary rows were added to allow drop down in glossary tab to go to each letter start, but, the sort on term up/down arrow is no longer working. Perhaps there is a better way to allow the user to get directly to a letter and still allow for sorting on terms. 
sandra444
=> Added glossary a to d in the help.html

microdevices/templates/microdevices/diseasemodel_detail.html
This was a change I had to make to get the image URL to work properly. My bad. 
Thanks again
=> Change to Image URL

assays/ajax.py, assays/models.py, assays/static/assays/assay_filter.js, assays/static/assays/assaymatrix_add.js, assays/static/assays/assaymatrixitem_add.js, assays/static/assays/assaystudy_reproducibility.js, assays/static/assays/assaystudy_summary.js, assays/static/assays/assaystudy_upload.js, assays/static/assays/chart_display.js, assays/static/assays/grouping_filtering.js, assays/templates/assays/assay_filter.html, assays/templates/assays/chart_options.html, assays/templates/assays/grouping_filtering.html, assays/urls.py, assays/utils.py, assays/views.py, bioactivities/templates/bioactivities/cluster.html, bioactivities/templates/bioactivities/heatmap.html, bioactivities/templates/bioactivities/table.html, compounds/static/compounds/compound_report.js, compounds/templates/compounds/compounds_report.html, drugtrials/static/drugtrials/compare_adverse_events.js, drugtrials/templates/drugtrials/adverse_events_list.html, drugtrials/templates/drugtrials/compare_adverse_events.html, mps/static/js/datatable_options.js, mps/templates/base.html, mps/templates/index.html, mps/templates/search/search.html, requirements.txt
Adds grouping and filtering.
Adds inter reproducibility.
=> Inter repro

drugtrials/ajax.py, drugtrials/static/drugtrials/auto_drug_trials_list.js, drugtrials/templates/drugtrials/auto_drug_trials.html
- Added result group information 
- Added restoration of field width after window size reformat 
- Appropriate formatting of condition and drug lists 
- Error resolved if no data on condition searched
=> Drug Trial Dynamic Pull Update

mps/templates/help.html
Have removed some of the definition type information from the help page and put it in the glossary (on the production database via the admin). FYI, I copied the whole body of the html file into a different editor, edited it, then copied the whole body back in.
=> Stage - changes to the Help page

mps/templates/help.html
Structure of the Help is in place. Working to fill in and revise/update content.
=> Help revisions

mps/templates/help.html
Ready to go on stage for review by team...still needs much content work....20180912:2048
=> Help revisions - Draft 3 with buttons

mps/templates/help.html
Lots of content changes and some tweaking of styles. 20180915.
=> help_revisions with more content and some tweaking of styles....20180915

mps/templates/base.html, mps/templates/help.html
help_revisions Adding more content to help. Rearranged the Nav bar. 2010926 Made small changes to the anchors in the base.html along with many changes to the help.html
=> help_revisions Adding more content to help. Rearranged the Nav bar. 2010926

mps/templates/help.html
Changes to two cells of a table in the help.html file. Minor changes.
=> Staging2 - minor changes

assays/static/assays/assay_filter.js, assays/static/assays/grouping_filtering.js, compounds/static/compounds/compound_report.js, compounds/templates/compounds/compounds_report.html, drugtrials/ajax.py, drugtrials/static/drugtrials/compare_adverse_events.js, drugtrials/templates/drugtrials/compare_adverse_events.html, mps/static/js/datatable_options.js
Should fix problems that arise when sorting checkboxes.
=> Fix Checkbox Sorting Issues

mps/templates/help.html
Adding video tutorials to Providing Data, steps 1 and 2 (add/edit study and add/edit matrix).
=> Adding video tutorials 

mps/templates/about.html, mps/templates/base.html, mps/views.py
Second version of the About page. Changes to data schedules proposed.
=> Second draft of the About page. A glossary style table added.

mps/templates/about.html
Incorporating some suggestions from Larry and making the navi bar match the subheadings.
=> Minor changes to About

mps/static/js/help.js, mps/templates/help.html
Changes to the Help. Added new features (collaborators, study sets, references) and did some reformatting to match better with the planned About page. Added a button at the bottom to open all collapsed buttons so it can be easily printed. Needs a complete read through.Team can review while sck is on vacation and can update when return.
=> Changes to Help - add new features. Format changes.

assays/forms.py, assays/models.py, assays/static/assays/assaymatrix_add.js, assays/static/assays/cell_sample_selection.js, assays/templates/assays/assaymatrix_add.html, cellsamples/ajax.py, cellsamples/models.py, cellsamples/static/cellsamples/cellsample_add.js, cellsamples/static/cellsamples/cellsample_list.js, cellsamples/templates/cellsamples/cellsample_add.html, mps/templates/errors.html
=> Minor Revisions

mps/static/js/help.js, mps/templates/help.html
Help videos moved to panopto. Spaces made for power analysis.
=> Help videos moved to panopto. Spaces made for power analysis.

assays/static/assays/assaystudy_upload.js, assays/templates/assays/assaystudy_upload.html
To review with L and Q for design agreement. First draft.
=> First draft of outline workflow for plate reader data processing tool

mps/templates/help.html
New version of help with PA and SDBTG. Needs proof reading.
=> Sandra help - needs proof reading

mps/templates/help.html
some changes made to styling of first part of help page plus some edits to study treatment by group and power analysis blurbs.
=> Help updates - PA and Study Setup

mps/templates/help.html
Minor change to references section of help
=> references update

assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/static/assays/assayplatereadermap_index.js, assays/templates/assays/assayplatereadermap_add.html
Should be fixes for labels and tooltips
=> fix labels and tool tips for stage

assays/ajax.py, assays/forms.py, assays/static/assays/assayplatereaderfile_update.js, assays/static/assays/assayplatereadermap_add.js, assays/static/assays/assayplatereadermap_index.js, assays/templates/assays/assayplatereaderfile_update.html, assays/templates/assays/assayplatereadermap_add.html, assays/templates/assays/assaystudy_index.html, assays/utils.py
some function changes to fix a few bugs and accomodate user requests.
=> mostly minor changes to page function and colors

assays/utils.py
to remove an error when saving a file with no plate map selected and follow pep
=> one small change

assays/ajax.py, assays/forms.py, assays/static/assays/assayplatereaderfile_update.js, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereaderfile_index.html, assays/templates/assays/assayplatereaderfile_update.html, assays/templates/assays/assayplatereadermap_add.html, assays/templates/assays/assayplatereadermap_index.html, assays/utils.py, assays/views.py
Mock up of data processing and mostly functioning plate map and files. Some features have not been well tested, but Mark wanted to see a mock up for the demo slides, so pushing it forward.
=> Sandra plate map

assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html
error in class (_ not -) to fix
=> what is checked when on the plate map add page

assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
=> messages for error finding

assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
no migration needed. added some qc and an a disappearing error message box.
=> added qc and error message box with zz concatenation instead of null

assays/utils.py
no migration - relatively minor changes
=> deal with 0 values in sample adjusted raw

assays/static/assays/assayplatereadermap_add.js, assays/utils.py
no migration needed. a few more small changes to deal with error catching of 0s.
=> a few more changes to deal with 0s

assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/utils.py
no migration needed. small changes to deal with errors when numbers are not realistic.
=> dealing with error in 4p logistic when have very small numbers

assays/ajax.py, assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
no migration required. Corrected several issues (change multiplier changes result, changed graphing of samples from raw to adjusted raw, added a different blank handling selection interface, added table of standards information, added more blank handling options)
=> corrected samples graph y axis and other updates

assays/forms.py, assays/models.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
migration recommended (did not change schema, but some of the other info in the models.py file. Fixed an issues with dom that wasn't in html for add map, staged ability to enter blanks a different way but did not fully do it (replicates are priority), made a few other changes (mostly in text on web page).
=> models clean up and a stage for blank changes and few other updates

assays/forms.py, assays/models.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
migration required - nothing major (extra info and defaults). Contains proposal for dealing with replicates.
=> changes for dealing with replicates.

assays/ajax.py, assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereaderfile_index.html, assays/templates/assays/assayplatereadermap_add.html, assays/templates/assays/assayplatereadermap_index.html, assays/utils.py
This version is the prep work for the guts of the average. Lots of todo and here here s to refine and flesh out. Will be good to get feedback on the page logic.
=> started the processing average

assays/ajax.py, assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py, assays/views.py
No migration needed. Should be ready for team review of design and testing. Robust testing is needed and will likely find issues with some of the lesser used features. Ready for stage.
=> Draft 3 of Replicate Handling

assays/ajax.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
A few more corrections to get stage and my box in line for testing of the blank behavior with Luke.
=> corrections show multiplier

assays/ajax.py, assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
No migration needed. Several corrections - multiplier and string, replicate averaging, sendmessage stringing, etc.
=> corrections to third draft of plate map interface V1

assays/static/assays/assayplatereadermap_add.js, assays/static/assays/assaystudy_list.js, assays/templates/assays/study_list.html, assays/utils.py, assays/views.py
No migration needed. Note that, the study list was changed so that the plate map and plate reader fields will show in the study list page. Luke, check those to make sure those changes are consistent with your preferences. Also changed so that, when doing logistic 4, the small values are null instead of the theoretical response at 0. A few other small changes.
=> Changes to show counts in Study List etc.

assays/utils.py
Correct a legacy error to multiple sample efflux instead of divide.
=> change / to * of sample efflux collected volume

assays/forms.py, assays/static/assays/assayplatereadermap_add.js, assays/utils.py
Changing some of the form fields to string to reduce chances of null causing errors in number fields.
=> Change to strings.

assays/forms.py, assays/views.py
No migration required. Correcting an unknown user error when submit to the study summary.
=> Correct unknown user error on submit

assays/utils.py
The root was not always pulling correctly so changed the way. Used a mid point to decide which was the better root.
=> changed why root is selected for poly2

assays/forms.py, assays/utils.py, assays/views.py
quickly moved save to the views from forms
=> moved save to views.py

assays/admin.py, assays/ajax.py, assays/forms.py, assays/models.py, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereaderfile_index.html, assays/templates/assays/assayplatereadermap_add.html, assays/templates/assays/assayplatereadermap_index.html, assays/utils.py, assays/views.py
Please delete all rows of the AssayPlateReaderMapItemValue model. Then, migration required. Major changes, included changing all linking between the AssayPlateReaderMapItem and AssayPlateReaderMapItemValue tables. Made many changes to fix bugs, biggest in the accumulation of the replicate groups. Changed formatting of strings in tables in js. Added logistic4a0. Completely removed the map item VALUE formset from the add platemap (and completely changed the way the data are added to the AssayPlateReaderMapItemValue model (in the bulk add). Instead of pulling from a set of rows in the Value table where the file block was null, made the set directly from the MapItem table. Overwrote the sample time, if needed during that process. Should provide more robustness. Add map page load should also …
=> Sandra plate map Major Changes

assays/static/assays/assayplatereadermap_add.js, assays/utils.py
minor code changes to try to fix table behavior.
=> minor changes to fix table response

assays/static/assays/assayplatereadermap_add.js, assays/utils.py
Minor changes which mostly all ended up as just comments. A few minor things, including get the D4a0 to show in the table (it was misnamed in the utils.py file).
=> minor changes - get D4a0 to show in table

assays/ajax.py, assays/forms.py, assays/static/assays/assayplatereaderfile_update.js, assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereaderfile_add.html, assays/templates/assays/assayplatereaderfile_update.html, assays/templates/assays/assayplatereadermap_add.html, assays/templates/assays/assayplatereadermap_index.html, assays/utils.py, assays/views.py
No migration required. Changes to the views pages, the colors in the plate map for well use (as per Mike C request), correction to the view of the plate map file data (was not showing data), and added a new 4P option to set lower and upper bounds. Needs QC but want to see if the process meets the request by Tongying.
=> changes to colors, views, add logistic4pf

assays/templates/assays/assayplatereadermap_index.html
One small change back of accidental bug introduction.
=> view to reveiw in platemap index

assays/static/assays/assayplatereadermap_add.js, assays/templates/assays/assayplatereadermap_add.html
Add a try/catch block to fix a bug.
=> add try block small bug fix

assays/utils.py
Making a runtime warning an error so it is trappable.
=> runtime warning to error and back

mps/templates/help.html
Adding two video presentations to the help page.
=> added two presentations to the help page

assays/ajax.py, assays/forms.py, assays/models.py, assays/static/assays/assayomicdatafileupload_aur.js, assays/templates/assays/assayomicdatafileupload_aur.html, assays/templates/assays/assayomicdatafileupload_index.html, assays/utils.py
Should not need a migration. Changes to the GUI including fixes of minor bugs. Rearranged code and moved some code to sub functions. Added a little more QC.
=> Changes to the GUI - only label changes to models

assays/admin.py, assays/forms.py, assays/models.py, assays/static/assays/assayomicdatafileupload_aur.js, assays/static/assays/assayomicdatafileupload_index.js, assays/templates/assays/assayomicdatafileupload_aur.html, assays/templates/assays/assayomicdatafileupload_delete.html, assays/templates/assays/assayomicdatafileupload_index.html, assays/utils.py, assays/views.py
Migration required (basic structure of models is same - I think - but changed some required fields and other such stuff). Bug fix to include upload of padj (<6 replaced <5). Moved a lot of code to sub functions to make it easier to expand to different data types. Did preliminary work to accept norm and raw counts data. Need some decisions from team (what required as file headers and what will be stored - we will need to decide on separate table or combined data points table). Built some upload GUI page logic to support different data types (what is hidden and what is shown as required). Will need to tweak when phase 2 if moving forward.
=> changes prepping for phase 2 and bug fix

assays/models.py, assays/static/assays/assayomicdatafileupload_aur.js, assays/templates/assays/assayomicdatafileupload_aur.html, assays/templates/assays/assayomicdatafileupload_index.html
Needs migration for extra stuff not table structures. Mostly minor changes as per Mark's requests.
=> Genome2020

assays/models.py, assays/static/assays/assayomicdatafileupload_aur.js, assays/templates/assays/assayomicdatafileupload_aur.html
shorten labels so do not wrap (some in models.py, but no table changes). change page logic behavior
=> Small changes

assays/admin.py, assays/ajax.py, assays/forms.py, assays/models.py
Migration required. Will pull from treatment groups instead of the temporary data groups.
=> changing to use treatment groups

assays/static/assays/assayomicdatafileupload_aur.js, assays/templates/assays/assayomicdatafileupload_aur.html
Minor change to hide hover tips about counts data.
=> hiding counts tips

mps/templates/help.html, resources/admin.py, resources/forms.py, resources/models.py
Migration needed for a uniqueness constraint. Other changes to make the glossary behave more like want.
=> A few additional changes to glossary/help

mps/views.py, resources/admin.py, resources/forms.py, resources/models.py
changing the help text and removing duplicate list.
=> a few small changes

resources/admin.py, resources/models.py
Some changes to make it easier to add terms to the glossary and also new choices for categories and Mark friendly names for categories.
=> Help2020 glossary model

assays/static/assays/assayomicdatafileupload_aur.js, assays/static/assays/assaystudy_list.js, assays/static/assays/assaystudyset_add.js, assays/static/assays/assaystudyset_data_plots.js, assays/templates/assays/study_list.html, assays/views.py
Some minor changes (change extension of file download, added conditional so null file doesn't make a preview error) and changed the Study List page so that the omic counts are listed.
=> change file extension, conditional preview, counts on study page

assays/forms.py, assays/templates/assays/assayomicdatafileupload_index.html
Just a couple of minor things (a bug fix and using intcomma)
=> couple minor fixes

mps/templates/help.html
Only changes to the help.html to get the video and QandA on the help page.
=> Webinar and QandA added

mps/templates/help.html
=> small change

mps/templates/help.html
Getting the webinar video and q and a on the help page.
=> Help2020 glossary model - help.html only

mps/templates/help.html
sorry - noticed an indent and realized missing a closing div - sorry sorry sorry
=> sorry, missing a closing div!

assays/ajax.py, assays/forms.py, assays/models.py, assays/static/assays/assayomicdatafileupload_aur.js, assays/templates/assays/assayomicdatafileupload_aur.html, assays/utils.py
This has some fairly significant changes to the logic (added a bunch of QC and option narrowing) and also to the storage location for the files (included a subfolder of study pk). Ready for testing on stage. No changes to tables but some non-structure stuff in models.py.
=> Sandra joint omics redo - add bunch of QC

assays/static/assays/assayomicdatafileupload_aur.js
Getting rid of an error that resulted for trying to get sample information when the group was changed to null
=> Sandra joint omics redo

assays/ajax.py, assays/static/assays/assayomicdatafileupload_aur.js, assays/utils.py
Moving a function to utils.py from ajax.py. A few other minor changes.
=> a few small fixes

resources/models.py
minor change - add two options to choices for help category
=> add two options for help category

assays/ajax.py, assays/forms.py, assays/models.py, assays/templates/assays/assayplatereadermap_add.html, assays/utils.py
The following were correct: change to lockable model for uploaded files, change some error messages, add some try blocks to keep error from going to server, deal with null form field when doing form save.
=> bug fixes found by Mike C on 20201104

assays/forms.py
There were changes made during integration of the plate map app to production that affected the column headers. Also, the column headers appear to have changed (maybe just their location???) from the time the plate map app was put on production until now. To track down the error that was being generated on stage on 20201104, pulled master to a new branch in local box, was able to reproduce the error, using what was on master and what was working in my box on platemap2020, changed the why the column headers were being used and manipulated. Note that, if COLUMN_HEADERS changes, this might break, it depends on the change.Please put this on STAGE for review and confirmation that it is working before moving to production. Thanks.
=> bug fix header names

resources/admin.py
sorry, one more thing to make editing links a bit easier - I will change this back after I edit the links (it is kind of ugly this way). Thanks.
=> make links editable in list for easy update for now

mps/templates/help.html, mps/views.py
A few more changes to make things work more correctly.
=> few more changes for stage

mps/templates/help.html
This was requested to go directly to production. It just adds webinar 2 and the QandA for webinar 2 to help.
=> add webinar 2 to help

mps/static/js/help.js, mps/templates/help.html, mps/templates/help_superuser_content.html, mps/views.py
Updating data sharing and a few other changes.
=> Help2020 - update data sharing

mps/templates/help.html, mps/templates/help_superuser_content.html
Just a few more content changes
=> Help Page - a few more content changes

mps/static/js/help.js, resources/models.py
put the anchor function in the link function that was for the glossary
=> change location of anchor function

mps/static/js/help.js, mps/templates/about.html, mps/templates/help.html, mps/templates/help_superuser_content.html, mps/views.py
Changes to get ready to move to production. Would like to review on stage before push to production (the links will not work correctly on stage, but that is okay for now).
=> Help2020 - getting ready for push

mps/templates/help.html
A few changes to add missing video and make place for next webinar.
=> added another video and place for next webinar

mps/templates/help.html
Changes to add webinar 3 to the help page (and some reference to webinar 3).
=> adding webinar 3
